jwt:
  secret: f232@Gg2f32HJ*_56538fj2W@FJ@fmf9F@2ri92IT2tjf$@@fev

server:
  servlet:
    session:
      timeout: 5m


spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: taskmanagementserviceteam@gmail.com
    password: sormvbtcaldrbltc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
