spring:
  datasource:
    # PostgreSQL configuration
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: '1234'
  sql:
    init:
      mode: always
  mustache:
    check-template-location: 'false'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true

# Launch the default browser when starting the application in development mode
vaadin:
  launch-browser: 'true'
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,pu.master.tmsgui

server:
  port: '8080'
logging:
  level:
    root: info


