spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/tms
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.format_sql: true

server:
  port: 8080

logging:
  level:
    root: info

jwt:
  secret: f232@Gg2f32HJ*_56538fj2W@FJ@fmf9F@2ri92IT2tjf$@@fev